# Generated by Django 5.0.6 on 2025-05-11 23:16

import finca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0004_alter_post_options_rename_user_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=finca.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=finca.models.user_directory_path),
        ),
    ]
